import { ObtainType, Set } from "../types/interfaces";

const sets_2: Set[] = [
  {
    id: "fashion__set__emperor_of_snow",
    name: "Emperor of Snow",
    starRank: 6,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseSnowDome,
    mainStyle: Style.pure,
    items: {
      create: [
        "fashion__hairstyle__dance_of_snow",
        "fashion__dress__emperor_of_snow",
        "fashion__socks__illusion_of_snow",
        "fashion__shoes__flowing_light",
        "fashion__earrings__whisper_of_snow",
        "fashion__gloves__snowy_fantasy",
        "fashion__hat__blizzard_sonata",
        "fashion__necklace__engraving_of_snow",
        "fashion__ring__snow_coagulation",
        "fashion__handheld__jade_fan",
        "fashion__tattoo__crystal_fantasy",
      ],
    },
  },
  {
    id: "fashion__set__winds_whisper",
    name: "Wind's Whisper",
    starRank: 6,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseBeloved,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__song_of_sunrise",
        "fashion__dress__winds_whisper",
        "fashion__socks__falling_feathers",
        "fashion__shoes__flutter_feather",
        "fashion__hat__crown_of_tides",
        "fashion__necklace__pearl_tides",
        "fashion__gloves__tears_of_star",
        "fashion__ring__heart_of_tides",
        "fashion__handheld__dancing_butterfly",
      ],
    },
  },
  {
    id: "fashion__set__feather_flower",
    name: "Feather Flower",
    starRank: 6,
    brandId: "evening_star",
    obtainType: ObtainType.exchangeFashionShop,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__hairstyle__snow_poem",
        "fashion__dress__feather_flower",
        "fashion__shoes__spring_vine",
        "fashion__hair__flower_picking",
        "fashion__earrings__morning_dew",
        "fashion__wrist__morning_flowers",
        "fashion__wings__fluttering_dream",
        "fashion__tattoo__floral_language",
      ],
    },
  },
  {
    id: "fashion__set__flowery_dream",
    name: "Flowery Dream",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.craftMindTravel,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__flowery_blessing",
        "fashion__dress__flowery_dream",
        "fashion__socks__hidden_trail",
        "fashion__shoes__wandering_flowers",
        "fashion__necklace__flowery_fence",
        "fashion__ring__weary_flowers",
      ],
    },
  },
  {
    id: "fashion__set__dream_poetry",
    name: "Dream Poetry",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.event,
    eventId: "event__shoppe_master",
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__hairstyle__flowing_dream",
        "fashion__dress__dream_poetry",
        "fashion__shoes__pure_poetry",
        "fashion__coat__hollow_flower",
        "fashion__earrings__dream_of_butterflies",
        "fashion__wrist__rosy_dream",
        "fashion__ring__dream_date",
      ],
    },
  },
  {
    id: "fashion__set__moonglow_sonata",
    name: "Moonglow Sonata",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.exchangeFashionShop,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__music_of_keys",
        "fashion__dress__moonglow_sonata",
        "fashion__socks__moonlight_organ",
        "fashion__shoes__nights_lovesong",
        "fashion__hat__star_concerto",
        "fashion__necklace__moon_heart_lock",
      ],
    },
  },
  {
    id: "fashion__set__floral_song",
    name: "Floral Song",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.rebateGift,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__love_song",
        "fashion__dress__floral_song",
        "fashion__socks__dream_land",
        "fashion__shoes__fence_love",
        "fashion__hat__white_romance",
      ],
    },
  },
  {
    id: "fashion__set__plaids_secret",
    name: "Plaid's Secret",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.craftMindTravel,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__ceylon_short_song",
        "fashion__dress__plaids_secret",
        "fashion__shoes__migrating_birds",
        "fashion__coat__misty_night",
        "fashion__hat__houndstooth",
        "fashion__necklace__red_snow",
        "fashion__handheld__night_black_tea",
      ],
    },
  },
  {
    id: "fashion__set__disturbed_night",
    name: "Disturbed Night",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.exchangeDecomStore,
    mainStyle: Style.pure,
    items: {
      create: [
        "fashion__hairstyle__windy_day",
        "fashion__dress__disturbed_night",
        "fashion__shoes__night_step",
        "fashion__hair__night_knitter",
        "fashion__earrings__night_chatter",
        "fashion__necklace__halt_of_breeze",
        "fashion__gloves__carved_night",
        "fashion__handheld__fragrance_of_lily",
      ],
    },
  },
  {
    id: "fashion__set__phoenix_arrival",
    name: "Phoenix Arrival",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseBeloved,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__cloud_palace",
        "fashion__dress__phoenix_arrival",
        "fashion__socks__phoenix",
        "fashion__shoes__immortal_moon",
        "fashion__face__jade_curtain",
        "fashion__hat__grand_ambition",
        "fashion__hair__moon_palace",
        "fashion__earrings__luminous_pearl",
        "fashion__ring__graceful_finger",
        "fashion__handheld__cloud_immortal",
      ],
    },
  },
  {
    id: "fashion__set__crane_dance",
    name: "Crane Dance",
    starRank: 5,
    brandId: "evening_star",
    obtainType: ObtainType.exchange,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__cloud_pile",
        "fashion__dress__crane_dance",
        "fashion__socks__crane_whisper",
        "fashion__shoes__crane_feather",
        "fashion__earrings__pear_blossom",
        "fashion__necklace__willow_twig",
      ],
    },
  },
  {
    id: "fashion__set__pandan_island",
    name: "Pandan Island",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.exchangeGuildShop,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__top__pandan_island",
        "fashion__bottom__ode_to_orchids",
        "fashion__socks__soft_drizzle",
        "fashion__shoes__blue_stream",
        "fashion__wrist__refined_flower",
        "fashion__anklet__bluebell_traveller",
      ],
    },
  },
  {
    id: "fashion__set__sky_toffee",
    name: "Sky Toffee",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__top__sky_toffee",
        "fashion__bottom__fluffy_milk_ball",
        "fashion__socks__deep_moon",
        "fashion__shoes__fluffy_night_dream",
      ],
    },
  },
  {
    id: "fashion__set__plum_age",
    name: "Plum Age",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.rebateGift,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__dress__plum_age",
        "fashion__shoes__plum_serenade",
        "fashion__earrings__emerald_light",
        "fashion__ring__wheel_of_age",
        "fashion__handheld__leafy_park",
      ],
    },
  },
  {
    id: "fashion__set__dance_of_tides",
    name: "Dance of Tides",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.event,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__top__dance_of_tides",
        "fashion__bottom__tide_in_dusk",
        "fashion__socks__deep_sea_foam",
        "fashion__shoes__starry_sea_hunting",
        "fashion__hat__teardrop_of_sea",
      ],
    },
  },
  {
    id: "fashion__set__long_ballad",
    name: "Long Ballad",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.event,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__dress__long_ballad",
        "fashion__shoes__shadow_steps",
        "fashion__earrings__crystal_stardew",
        "fashion__necklace__valley_bamboo",
        "fashion__ring__shimmering_bud",
      ],
    },
  },
  {
    id: "fashion__set__hustle_and_bustle",
    name: "Hustle and Bustle",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseNightOfVvanna,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__top__hustle_and_bustle",
        "fashion__bottom__neon_lights",
        "fashion__socks__twinkling_stars",
        "fashion__shoes__bustling_night",
        "fashion__coat__lighted_night",
        "fashion__handheld__dark_street",
      ],
    },
  },
  {
    id: "fashion__set__chapter_seven",
    name: "Chapter Seven",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__dress__chapter_seven",
        "fashion__shoes__ode_to_butterfly",
        "fashion__hair__rosy_wings",
        "fashion__gloves__silk_dream",
      ],
    },
  },
  {
    id: "fashion__set__midsummer_sky",
    name: "Midsummer Sky",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__dress__midsummer_sky",
        "fashion__socks__summer_breeze",
        "fashion__shoes__tree_shadow",
        "fashion__handheld__girls_tea_party",
      ],
    },
  },
  {
    id: "fashion__set__silver_plaid",
    name: "Silver Plaid",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__dress__silver_plaid",
        "fashion__shoes__old_song",
        "fashion__necklace__purewhite_teardrop",
        "fashion__gloves__silver_face",
      ],
    },
  },
  {
    id: "fashion__set__heart_iris",
    name: "Heart Iris",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseNightOfVvanna,
    mainStyle: Style.sexy,
    items: {
      create: [
        "fashion__hairstyle__iris_dream",
        "fashion__dress__heart_iris",
        "fashion__shoes__iris_road",
        "fashion__earrings__inner_words",
      ],
    },
  },
  {
    id: "fashion__set__night_gibberish",
    name: "Night Gibberish",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.simple,
    items: {
      create: [
        "fashion__dress__night_gibberish",
        "fashion__socks__starless_night",
        "fashion__shoes__shining_poem",
        "fashion__earrings__the_nocturne",
        "fashion__handheld__midnight_murmur",
      ],
    },
  },
  {
    id: "fashion__set__plain_moon",
    name: "Plain Moon",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__laurel",
        "fashion__dress__plain_moon",
        "fashion__socks__toe_and_moon",
        "fashion__shoes__moonlight",
        "fashion__hat__cloudy_night",
        "fashion__hair__long_longing",
        "fashion__necklace__moon_of_hearts",
        "fashion__ring__autumn_moon",
      ],
    },
  },
  {
    id: "fashion__set__queen_of_snow",
    name: "Queen of Snow",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.craftStoryQuest,
    mainStyle: Style.sexy,
    items: {
      create: [
        "fashion__hairstyle__shining_night",
        "fashion__dress__queen_of_snow",
        "fashion__shoes__snow_region",
        "fashion__hat__crown_of_darkness",
        "fashion__bracelet__northern_anthem",
        "fashion__gloves__snow_and_owl",
      ],
    },
  },
  {
    id: "fashion__set__florescence",
    name: "Florescence",
    starRank: 4,
    brandId: "evening_star",
    obtainType: ObtainType.lightchaseNightOfVvanna,
    mainStyle: Style.elegant,
    items: {
      create: [
        "fashion__hairstyle__coiled_topknot",
        "fashion__dress__florescence",
        "fashion__socks__snow_of_pear",
        "fashion__shoes__sunshine_floret",
      ],
    },
  },
];
